name: Bug report
description: Report a problem with the app
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: "e.g. v1.0.3"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the issue and the steps to reproduce it.
      placeholder: "Steps:\n1) ...\n2) ...\nExpected: ...\nActual: ..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or add screenshots.
      render: shell
